pipeline:
    unittests:
        image: ${IMAGE}
        environment:
            - PYTEST_ADDOPTS=--color=yes
        commands:
            - pip3 install -r requirements.txt -r requirements-tests.txt
            - py.test --cov=soa --cov-report=term

    pylint:
        image: ${IMAGE}
        environment:
            - PYTEST_ADDOPTS=--color=yes
        commands:
            - pip3 install -r requirements.txt -r requirements-tests.txt
            - py.test --pylint soa
        when:
            matrix:
                # only need to run lint once
                IMAGE: python:3.5

matrix:
    IMAGE:
        - python:3.4
        - python:3.5
